ingress:
  hostname: ip.linux.plus
  tls: false
service:
  name: ip-linux
deployment:
  name: ip-linux
  replica: 2
  image:
    repository: repo.treescale.com/liuxu/ip.linux.plus:latest
    pullPolicy: Always
    pullSecret: treescale


