apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deployment.name }}
  labels:
    app: {{ .Values.deployment.name }}
spec:
  replicas: {{ .Values.deployment.replica }}
  selector:
    matchLabels:
      app: {{ .Values.deployment.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.deployment.name }}
      annotations:
        rollme: {{ randAlphaNum 5 | quote }}
    spec:
      imagePullSecrets:
        - name: {{ .Values.deployment.image.pullSecret }}
      containers:
        - name: nginx
          image: {{ .Values.deployment.image.repository }}
          imagePullPolicy: {{ .Values.deployment.image.pullPolicy | quote }}
          ports:
          - containerPort: 80